[theme]
base = "light"
primaryColor = "#0D47A1"         # Optional: deep blue
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#000000"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
